Purpose: Look at GO enrichment results for HybridExpress-TS gene intersections of each physiotype of *Y. gloriosa*.<br>
Author: Anna Pardo<br>
Date initiated: May 11, 2026

In [1]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
from venn import venn

In [2]:
# load results
res = pd.read_csv("./GOenrichres_HybExp_TS_intgenes.txt",sep="\t",header="infer")
res.head()

,p.value,GO.term,p.adj,regset,Ontology,Term,Annotated,Significant,Expected,result1,Descr
0,1.389017e-16,GO:0006091,1.224592e-13,CAM_TS_UP,BP,generation of precursor metabolites and ...,594,47,11.15,1.400000e-16,generation of precursor metabolites and energy
1,3.990088e-05,GO:0006139,5.862935e-03,CAM_TS_UP,BP,nucleobase-containing compound metabolic...,7000,173,131.41,4.000000e-05,nucleobase-containing compound metabolic process
2,3.625731e-04,GO:0006950,3.706128e-02,CAM_TS_UP,BP,response to stress,4418,113,82.94,3.600000e-04,response to stress
3,1.078826e-18,GO:0007623,1.521792e-15,CAM_TS_UP,BP,circadian rhythm,246,33,4.62,1.100000e-18,circadian rhythm
4,3.719619e-17,GO:0008150,3.747782e-14,CAM_TS_UP,BP,biological_process,22867,521,429.27,3.700000e-17,biological_process

In [4]:
res.groupby("regset").count().reset_index()[["regset","GO.term"]].sort_values(by="GO.term",ascending=False)

                       regset  GO.term
4                C3+CAM_TS_UP       97
1              C3+CAM_TS_DOWN       91
7               CAM_TS_ELD_P1       87
6                 CAM_TS_DOWN       84
9                   CAM_TS_UP       77
2            C3+CAM_TS_ELD_P1       76
3            C3+CAM_TS_ELD_P2       68
8               CAM_TS_ELD_P2       44
0               C3+CAM_TS_ADD       29
5                  CAM_TS_ADD       20
11  facultative_CAM_TS_ELD_P1       12
10    facultative_CAM_TS_DOWN        5
12  facultative_CAM_TS_ELD_P2        3