Purpose: Make a unified list of all SRR numbers used for this project.<br>
Author: Anna Pardo<br>
Date initiated: Mar. 19, 2026

In [1]:
import pandas as pd
import os

In [2]:
# load Yg TPM - all samples, not subset
alltpm = pd.read_csv("/home/leviathan22/Yucca_genomics/rna_insilico_genome/TPM/Yg_toYgIS_allTPM_md_over1mil.txt",
                    sep="\t",header="infer",usecols=["sample_name","genotype","time","treat","ZT","species"])

/tmp/ipykernel_32590/2311060922.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  alltpm = pd.read_csv("/home/leviathan22/Yucca_genomics/rna_insilico_genome/TPM/Yg_toYgIS_allTPM_md_over1mil.txt",

In [3]:
alltpm.head()

   sample_name genotype  time treat    ZT   species
0           Y1       18   1.0     W   1.0  gloriosa
1          Y10      2AB   1.5     W   3.0  gloriosa
2         Y100      2AB   6.5     W  23.0  gloriosa
3  SRR10848707       55   4.0     D  13.0  gloriosa
4  SRR10848820       70   4.0     D  13.0  gloriosa

In [4]:
srr_from_tpm = []
for i in alltpm["sample_name"].unique():
    if i.startswith("S"):
        srr_from_tpm.append(i)

In [5]:
len(srr_from_tpm)

371

In [6]:
# merge with a couple existing files
yaygsrr = list(pd.read_csv("/home/leviathan22/Yucca_genomics/Ya_Yg_SRR_download.txt",sep="\t",header=None)[0])
yaygsrr[0]

'SRR30854473'

In [10]:
len(yaygsrr)

58

In [11]:
allsrr = list(set(srr_from_tpm).union(set(yaygsrr)))
len(allsrr)

418

In [12]:
redown = list(pd.read_csv("./srr_redownload_07-Jul.txt",sep="\t",header=None)[0])

In [13]:
srrdown = list(pd.read_csv("./srr_download_rna_reanalysis.txt",sep="\t",header=None)[0])

In [14]:
rnajgi = list(pd.read_csv("./rnaseq_JGI_sra.txt",sep="\t",header=None)[0])

In [15]:
allsrr = set(allsrr).union(set(redown))

In [16]:
len(allsrr)

419

In [17]:
allsrr = allsrr.union(set(srrdown))
len(allsrr)

466

In [18]:
allsrr = allsrr.union(set(rnajgi))

In [19]:
len(allsrr)

466

In [20]:
missing = list(pd.read_csv("/home/leviathan22/Yucca_genomics/missing_metadata_samples_srr.txt",sep="\t",header=None)[0])
m2 = []
for i in missing:
    if i.startswith("S"):
        m2.append(i)

In [21]:
allsrr = allsrr.union(set(m2))
len(allsrr)

466

In [22]:
srrmd = pd.read_csv("/home/leviathan22/Yucca_genomics/srr_metadata_15-Aug-2025.csv",sep=",",header="infer")
srrmd.head()

   sample_name  genotype  time treat  ZT   species
0  SRR12424781        37   NaN   NaN NaN  gloriosa
1  SRR30853921        19   6.0     D NaN  gloriosa
2  SRR30853922        19   2.0     W NaN  gloriosa
3  SRR30853923        19   3.0     D NaN  gloriosa
4  SRR30853924        19   4.0     D NaN  gloriosa

In [23]:
s = []
for i in srrmd["sample_name"]:
    if i.startswith("S"):
        s.append(i)

In [24]:
allsrr = allsrr.union(set(s))
len(allsrr)

466

In [26]:
s2l = pd.read_csv("/home/leviathan22/Yucca_genomics/srr_to_libid.csv",sep=",",header="infer")
s2l.head()

           Run libid
0  SRR10663370  Y722
1  SRR10663371  Y723
2  SRR10663372  Y724
3  SRR10663373  Y746
4  SRR10663374  Y721

In [27]:
allsrr = allsrr.union(set(list(s2l["Run"])))
len(allsrr)

466

In [28]:
with open("./all_sra_ids_Yucca_19-Mar-2026.txt","w+") as outfile:
    for i in list(allsrr):
        outfile.write(i+"\n")