Purpose: Find out summary stats about the cluster groupings by ZT-peak.<br>
Author: Anna Pardo<br>
Date initiated: Dec. 15, 2025

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
cinfo = pd.read_csv("./clusters_ngenes_gt_ztgroup_with36-61-43.txt",sep="\t", header="infer")
cinfo.head()

   cluster genotype  n_CAM_genes  n_all_genes   gtc  ZTpeak
0        1       53          0.0          319  53_1     5.0
1        2       53          1.0          656  53_2    21.0
2        3       53          1.0          882  53_3    17.0
3        4       53          0.0         1071  53_4     9.0
4        5       53          0.0          428  53_5    21.0

In [7]:
cinfo["genotype"].unique()

array(['53', 'Eudy', '13', '52', '48', 'G', '19', '46', '56', '45', '18',
       '70', '1AB', '55', '51', '2AB', '37', 'all', '36', '61', '43'],
      dtype=object)

In [6]:
cinfo.groupby("ZTpeak").count().reset_index()[["ZTpeak","cluster"]].sort_values(by="cluster",ascending=False)

   ZTpeak  cluster
0     1.0       24
5    21.0       24
2     9.0       21
1     5.0       19
4    17.0       17
3    13.0       15