Purpose: Find, in OrthoFinder results, the Arabidopsis gene that corresponds to YufilH1061746m.g, a likely transcription factor found DE in both *Y. filamentosa* and CAM *Y. gloriosa*.<br>
Author: Anna Pardo<br>
Date initiated: June 10, 2026

In [6]:
gene = "YufilH1061746m"

In [2]:
import pandas as pd
import numpy as np
import json

In [3]:
# load orthogroup info
ogs = pd.read_csv("/home/leviathan22/Yucca_genomics/Orthogroups-Yucca_v3_7Oct2025.tsv",sep="\t",header="infer")
ogs.head()

/tmp/ipykernel_283/3322233443.py:2: DtypeWarning: Columns (1,2,3,4) have mixed types. Specify dtype option on import or set low_memory=False.
  ogs = pd.read_csv("/home/leviathan22/Yucca_genomics/Orthogroups-Yucca_v3_7Oct2025.tsv",sep="\t",header="infer")

,Orthogroup,Agave_tequiliana,Ananas_comosus,Arabidopsis_thaliana,Asparagus_officinalis_V1.1,Azolla_filiculoides,Brachypodium_distachyon_v3.2,Isoetes_taiwanensis,Kalanchoe_fedtschenkoi,Nymphaea_colorata,Oryza_sativa_v7.0,Peperomia_trollii,Phaelanopsis_equestris,Piper_nigrum,Portulaca_amilis,Yucca_aloifolia,Yucca_filamentosa_v3,Zea_mays
0,OG0000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Ptro.C001G1101.t1, Ptro.C001G1105.t1, Ptro.C00...",NaN,NaN,NaN,NaN,NaN,NaN
1,OG0000001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FUN_000003-T1, FUN_000004-T1, FUN_000086-T1, F...",NaN,NaN,NaN
2,OG0000002,AgateH1.13G059800.1.p,NaN,NaN,NaN,NaN,NaN,NaN,Kaladp0045s0190.1,NaN,NaN,"Ptro.C001G1024.t1, Ptro.C001G1025.t1, Ptro.C00...","PEQU_27888.1, PEQU_30808.1","Pn11.1296, Pn25.138, Pn7.1429","FUN_002586-T1, FUN_006253-T1",NaN,"YufilH1005191m, YufilH1008745m",NaN
3,OG0000003,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"FUN_000007-T1, FUN_000008-T1, FUN_000022-T1, F...",NaN,NaN,NaN
4,OG0000004,"AgateH1.03G030100.1.p, AgateH1.03G030200.1.p, ...","Aco018614.1, Aco021210.1, Aco021473.1","AT1G48980.1, AT2G17970.1, AT4G36090.3","evm.model.AsparagusV1_01.1455, evm.model.Aspar...",Afil_s0250.g060225,"Bradi1g51390.1.p, Bradi1g51390.2.p, Bradi1g513...","Itaiw.v1.c398g46803, Itaiw.v1.c57g43884","Kaladp0011s0113.1, Kaladp0040s0535.1",Nycol.B01543.1.p,"LOC_Os06g04660.1, LOC_Os06g04660.2","Ptro.C004G11237.t1, Ptro.C005G11726.t1","PEQU_00639.1, PEQU_00652.1, PEQU_00658.1, PEQU...","Pn12.147, Pn3.2614","FUN_008788-T1, FUN_025561-T1, FUN_025562-T1","Yucal.03G026500.1.p, Yucal.03G026600.1.p, Yuca...","YufilH1017244m, YufilH1017245m, YufilH1017246m...","Zm00001eb377750_P001, Zm00001eb377750_P002"

In [4]:
ogs = ogs[]
ogs.head()

,Orthogroup,Arabidopsis_thaliana,Yucca_aloifolia,Yucca_filamentosa_v3
0,OG0000000,NaN,NaN,NaN
1,OG0000001,NaN,NaN,NaN
2,OG0000002,NaN,NaN,"YufilH1005191m, YufilH1008745m"
3,OG0000003,NaN,NaN,NaN
4,OG0000004,"AT1G48980.1, AT2G17970.1, AT4G36090.3","Yucal.03G026500.1.p, Yucal.03G026600.1.p, Yuca...","YufilH1017244m, YufilH1017245m, YufilH1017246m..."

In [7]:
ogs.dropna(inplace=True)

In [9]:
og = []
for i in range(len(ogs.index)):
    if gene in ogs.iloc[i,3]:
        og.append(ogs.iloc[i,0])

In [10]:
ogs[ogs["Orthogroup"].isin(og)]

,Orthogroup,Arabidopsis_thaliana,Yucca_aloifolia,Yucca_filamentosa_v3
1574,OG0001574,AT3G54500.3,"Yucal.01G204800.1.p, Yucal.02G286000.1.p, Yuca...","YufilH1004829m, YufilH1004830m, YufilH1004831m..."