Purpose: Look at results of the maSigPro run on single reps of *Y. gloriosa* data.<br>
Author: Anna Pardo<br>
Date initiated: Apr. 9, 2026

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
res = pd.read_csv("./hck6_Yg_singlereps.tsv",sep="\t",header="infer")
res.head()

   cluster                GeneID
0        1  Yucal.01G000100.v2.1
1        2  Yucal.01G000200.v2.1
2        2  Yucal.01G000400.v2.1
3        1  Yucal.01G000500.v2.1
4        2  Yucal.01G000600.v2.1

In [3]:
# how many total unique time-structured genes?
len(res["GeneID"].unique())

51243

In [4]:
len(res.index)

51243

In [5]:
# add subgenome column
sg = []
for i in res["GeneID"]:
    if i.startswith("Yucal"):
        sg.append("Ya")
    else:
        sg.append("Yf")

In [6]:
res["subgenome"] = sg
res.head()

   cluster                GeneID subgenome
0        1  Yucal.01G000100.v2.1        Ya
1        2  Yucal.01G000200.v2.1        Ya
2        2  Yucal.01G000400.v2.1        Ya
3        1  Yucal.01G000500.v2.1        Ya
4        2  Yucal.01G000600.v2.1        Ya

In [7]:
len(res[res["subgenome"]=="Ya"].index)

27231

In [8]:
len(res[res["subgenome"]=="Yf"].index)

24012

## Apr. 13: Results of single-replicate run with 3 genotypes

In [2]:
res = pd.read_csv("./maSigPro_clusters_hclust_k6_Yg_3gt_1rep.txt",sep="\t",header="infer")
res.head()

   cluster                GeneID
0        1  Yucal.01G000400.v2.1
1        2  Yucal.01G000900.v2.1
2        3  Yucal.01G001500.v2.1
3        4  Yucal.01G001600.v2.1
4        4  Yucal.01G001700.v2.1

In [3]:
len(res["GeneID"].unique())

12436

In [4]:
# add subgenome column
sg = []
for i in res["GeneID"]:
    if i.startswith("Yucal"):
        sg.append("Ya")
    else:
        sg.append("Yf")

In [6]:
res["subgenome"]=sg

In [8]:
len(res[res["subgenome"]=="Ya"]["GeneID"].unique())

7663

In [9]:
len(res[res["subgenome"]=="Yf"]["GeneID"].unique())

4773